#! /usr/bin/env bash

for fname in `find . -type f | grep -iv \/node\_modules\/ | grep -Ei '\.(cc|cp?p?|hh|hp?p?|pyx?|z?sh|m?jsx?|jessie|json|(ya|to)ml)$'`; do
    cat<<<`cat "$fname" | sed 's/\t/    /g'`>"$fname"
done
